language: c
#######################################################################################
os:
  - linux
  
sudo: enabled

addons:
  apt:
    packages:
      - curl

#######################################################################################


before_install:

  - sudo apt-get update -qq
  
  - git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 ~/aarch64-linux-android-4.9/
  #- git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 ~/arm-linux-androideabi-4.9/
  - sudo chmod -R a+x *

#######################################################################################


script:  
  
  - export ARCH=arm64 export ARCH_MTK_PLATFORM=mt6735
  - export CROSS_COMPILE=~/aarch64-linux-android-4.9/bin/aarch64-linux-android-
  - export CONFIG=gnsz6753_66_n
  #- export KERNEL=kernel-3.18
  - KERNEL_DIR=$PWD/android_kernel_condor_gnsz6753_66_n
  - ZIMAGE=$KERNEL_DIR/arch/arm64/boot/zImage
  - export OUTDIR=out/target/product/$PROJECT/obj/KERNEL_OBJ
  - make -C O=$OUTDIR ROOTDIR=$ROOTDIR ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE ${CONFIG}_defconfig
  #- mkdir -p out
  #- make O=out clean
  #- make O=out mrproper
  #- make O=out gnsz6753_66_n_defconfig
  #- make O=out -j16
  #- make gionee6737t_66_m0_defconfig
  #- make gionee6735_65u_m0_defconfig
  #- make gnsz6737t_36g_n_defconfig
  #- bash build.sh
  #- make -j16
  #- make ARCH=arm64 -j16 clean mrproper

after_success:
  - curl --upload-file arch/arm64/boot/zImage https://transfer.sh/condor_gnsz6753_66_n_kernel
  
deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GIT_OAUTH_TOKEN_TB"
  
  on:
    tags: true
    repo: ALGPHELLO/android_kernel_condor_gnsz6753_66_n
    branch: Nougat

branches:
  except:
    - /^(?i:untagged)-.*$/
