sudo: required
language: cpp
compiler: gcc
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  - sudo apt-get install python-software-properties
  - sudo apt-get update -qq
  - sudo apt-get install gcc-4.9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 50
  - sudo apt-get install g++-4.9
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50
  
script: 
  - bash travis.sh

cache:
  - ccache

group: travis_latest
os: linux
 
